### ISSUE TITLE
deprecate the master branch

### ISSUE THREAD

**Issue by gbinal** [GSA/data.gov-styleguide#7]
It looks like the readme on the master branch could easily be brought into the readme of the gh-pages branch.  The master branch could then be deleted, making interactions with this repo easier.  

I'm happy to do if there aren't any complaints.  cc @philipashlock, @rebeccawilliams

**Comment by rebeccawilliams** [comment]
Go for it.

**Comment by gbinal** [comment]
Thanks!  Done.

**Comment by rebeccawilliams** [comment]
Thank you!
